In [1]:
import numpy as np
import numpy.linalg as la

### F<sub>n</sub> = F<sub>n-1</sub>+F<sub>n-2</sub>

$
\begin{pmatrix}F_n\\F_{n-1}\end{pmatrix}
=
\begin{pmatrix}1&1\\1&0\end{pmatrix}
\begin{pmatrix}F_{n-1}\\F_{n-2}\end{pmatrix}
$

$
\begin{pmatrix}F_1\\F_0\end{pmatrix}
=
\begin{pmatrix}1\\0\end{pmatrix}
$

$
\begin{pmatrix}F_n\\F_{n-1}\end{pmatrix}
=
\begin{pmatrix}1&1\\1&0\end{pmatrix}^{n-1}
\begin{pmatrix}1\\0\end{pmatrix}
$

In [2]:
A = np.array([
    [1, 1],
    [1, 0]
])
F1 = np.array([1, 0])
print("F50 =", (la.matrix_power(A, 49) @ F1)[0])

F50 = 12586269025


$
\mathbf{A}=
\begin{pmatrix}1&1\\1&0\end{pmatrix}
$

$
\mathbf{\Lambda}
=
\begin{pmatrix}\lambda_1&0\\0&\lambda_2\end{pmatrix}
$

$
\mathbf{V}=
\begin{pmatrix}\mathbf{v}_1&\mathbf{v}_2\end{pmatrix}
$

$
\begin{matrix}
\mathbf{A}\mathbf{v}_1
=
\lambda_1\mathbf{v}_1
\\
\mathbf{A}\mathbf{v}_2
=
\lambda_2\mathbf{v}_2
\end{matrix}
\Big\}
\Rightarrow
\mathbf{A}\mathbf{V}
=
\mathbf{V}\mathbf{\Lambda}
\Rightarrow
\mathbf{A}
=
\mathbf{V}\mathbf{\Lambda}\mathbf{V}^{-1}
\Rightarrow
\mathbf{A}^n
=
\mathbf{V}\mathbf{\Lambda}^n\mathbf{V}^{-1}
=
\mathbf{V}
\begin{pmatrix}\lambda_1^n&0\\0&\lambda_2^n\end{pmatrix}
\mathbf{V}^{-1}
$

$
\begin{pmatrix}F_n\\F_{n-1}\end{pmatrix}
=
\mathbf{V}
\begin{pmatrix}\lambda_1^{n-1}&0\\0&\lambda_2^{n-1}\end{pmatrix}
\mathbf{V}^{-1}
\begin{pmatrix}1\\0\end{pmatrix}
$

In [3]:
W, V = la.eig(A)
print("W =\n", W)
print("V =\n", V)
print("A =\n", V @ np.diag(W) @ la.inv(V))
print("F50 =", (V @ np.diag(np.power(W, 49)) @ la.inv(V) @ F1)[0])

W =
 [ 1.61803399 -0.61803399]
V =
 [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
A =
 [[ 1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -1.11022302e-16]]
F50 = 12586269025.000023


### F<sub>n</sub> = 2F<sub>n-1</sub>+1

$
\begin{pmatrix}F_n\\1\end{pmatrix}
=
\begin{pmatrix}2&1\\0&1\end{pmatrix}
\begin{pmatrix}F_{n-1}\\1\end{pmatrix}
$

$
\begin{pmatrix}F_0\\1\end{pmatrix}
=
\begin{pmatrix}0\\1\end{pmatrix}
$

$
\begin{pmatrix}F_n\\1\end{pmatrix}
=
\begin{pmatrix}2&1\\0&1\end{pmatrix}^n
\begin{pmatrix}0\\1\end{pmatrix}
$

In [4]:
A = np.array([
    [2, 1],
    [0, 1]
])
F0 = np.array([0, 1])
print("F20 =", (la.matrix_power(A, 20) @ F0)[0])

F20 = 1048575


In [8]:
A = np.array([
    [2, 1],
    [0, 1]
])
W, V = la.eig(A)
print("W =\n", W)
print("V =\n", V)
print("A =\n", V @ np.diag(W) @ la.inv(V))
print("F20 =", (V @ np.diag(np.power(W, 20)) @ la.inv(V) @ F0)[0])

W =
 [2. 1.]
V =
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]
A =
 [[2. 1.]
 [0. 1.]]
F20 = 1048575.0
